### ISSUE TITLE
More of a question than an issue. 

### ISSUE THREAD

**Issue by michaelochurch** [sdiehl/tinyjit#1]
This is really cool stuff. I have one question that comes to mind, and I might not be getting what's going on. 

For this code, posted to [your recent essay](http://www.stephendiehl.com/posts/monads_machine_code.html)

```
loop :: Val -> X86()
loop (A dst) = do
  emit [0xE2]
  src <- gets _memoff
  ptr <- gets _memptr
  emit [fromIntegral $ dst - src]
```

Since `emit` takes a `[Word8]`, isn't this liable to generate incorrect code if `dest - src` is outside of range (a longer jump than 127/128 bytes)? In fact, since `Word8` is unsigned, I believe that overflow is technically already happening (-4 to 252) in the example given; it's harmless in this case, because the bit pattern `0xfc` is preserved either way.

**Comment by sdiehl** [comment]
I should probably clarify in the article, the `loop` instruction makes for a nice short factorial function because it works for _short jumps_. Its operand code is `rel8` so one signed byte at the machine level. Because relative offset is signed 0x00 to 0x7F is for forward jumps, and from 0x80 to 0xFF for backwards jumps. 

So yes, it's possible that this will overflow if you give it a destination that's too far. So what I'll write about next is how we guarantee this invariant when we choose the right `jmp` or `loop` instruction from the higher level AST.
